version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
      - dotnet-packages:/home/vscode/.nuget/packages
    command: sleep infinity
    ports:
      - "5264:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - DOTNET_USE_POLLING_FILE_WATCHER=true
      - DOTNET_WATCH_SUPPRESS_LAUNCH_BROWSER=true
      - ConnectionStrings__HajjSystemConnectionString=Host=hajj-db-dev-2;Port=5432;Database=db1;Username=user1;Password=password1
    depends_on:
      hajj-db-dev-2:
        condition: service_healthy

  hajj-db-dev-2:
    image: postgres:14.5
    container_name: hajj-db-dev-2
    restart: unless-stopped
    command: postgres -c 'max_connections=500'
    ports:
      - "7074:5432"
    volumes:
      - "../db_data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_PASSWORD=password1
      - POSTGRES_USER=user1
      - POSTGRES_DB=db1
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user1 -d db1"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  dotnet-packages:
